### ISSUE TITLE
Loosing progress with screen roation.

### ISSUE THREAD

**Issue by bhagath555** [JayaSuryaT/minesweeper-j-compose#44]
Hi Jaya,
The game is enjoyable, and moving gradient over cells is pleasing. Good job.
But, the issue that I want to bring here is : If I play the game with autorotation turned on, every time I tilt the phone, the game is getting rotated, and I am losing progress. Please fix this.
You can either make the game unaffected by screen rotation or keep the progress even after rotating the screen.

**Comment by JayaSuryaT** [comment]
Hey @bhagath555!
Thank you for the praise.

Good catch! 👌. Actually, the game doesn't properly yet support `landscape orientation`. I usually have my auto-rotation turned off 😁, so I never encountered this issue, my bad.

I think, for now, I'll disable the rotation of the game so users no longer will have this issue. I'll reconsider adding it as a new feature in future releases tho.

###### (This issue will be fixed in [v1.0.0-alpha02](https://github.com/JayaSuryaT/minesweeper-j-compose/milestone/2) release)
